[project]
name = "permit-flexible-frontend"
authors = ["Frontend Permit Team"]
description = "A Clarity smart contract for flexible, dynamic frontend permission management"
telemetry = false
requirements = []
[contracts.permit-flexible-frontend]
path = "contracts/permit-flexible-frontend.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
